codecov:
  notify:
    require_ci_to_pass: true
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    project:
      default:
        threshold: 20
    patch: false
    changes: false
ignore:
  - "vendor"
  - "**.proto"
  - "**.pb.go"
comment:
  behavior: default
  layout: header, diff
  require_changes: false
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
