language: go

go:
  - 1.8

script:
  - make test-pki
  - make test-public
  - make build
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

notifications:
  email:
    on_success: change
    on_failure: always
