RootCertLoc = "private/root-cert.pem"


[IMAP]
Greeting = "Pluto ready."
HierarchySeparator = "."


[Distributor]
Name = "eu-west-distributor"
PublicMailAddr = "127.0.0.1:19933"
ListenMailAddr = "127.0.0.1:19933"
PrometheusAddr = "127.0.0.1:9001"
PublicCertLoc = "private/public-distributor-cert.pem"
PublicKeyLoc = "private/public-distributor-key.pem"
InternalCertLoc = "private/internal-distributor-cert.pem"
InternalKeyLoc = "private/internal-distributor-key.pem"
AuthAdapter = "AuthFile"

    [Distributor.AuthFile]
    File = "test-users.txt"
    Separator = ";"


[Workers]

    [Workers.worker-1]
    Name = "eu-west-worker-1"
    PublicMailAddr = "127.0.0.1:20001"
    ListenMailAddr = "127.0.0.1:20001"
    PublicSyncAddr = "127.0.0.1:30001"
    ListenSyncAddr = "127.0.0.1:30001"
    PrometheusAddr = "127.0.0.1:9001"
    CertLoc = "private/internal-worker-1-cert.pem"
    KeyLoc = "private/internal-worker-1-key.pem"
    UserStart = 1
    UserEnd = 10
    MaildirRoot = "private/Maildirs/worker-1/"
    CRDTLayerRoot = "private/crdt-layers/worker-1/"

    [Workers.worker-1.Peers.subnet-1]
    us-west-worker-1 = "127.0.0.1:30101"
    asia-south-worker-1 = "127.0.0.1:30201"
    storage = "127.0.0.1:31000"


[Storage]
Name = "storage"
PublicMailAddr = "127.0.0.1:21000"
ListenMailAddr = "127.0.0.1:21000"
PrometheusAddr = "127.0.0.1:9001"
CertLoc = "private/internal-storage-cert.pem"
KeyLoc = "private/internal-storage-key.pem"
MaildirRoot = "private/Maildirs/storage/"
CRDTLayerRoot = "private/crdt-layers/storage/"

    [Storage.SyncAddrs.subnet-1]
    Public = "127.0.0.1:31000"
    Listen = "127.0.0.1:31000"

    [Storage.Peers.subnet-1]
    eu-west-worker-1 = "127.0.0.1:30001"
    us-west-worker-1 = "127.0.0.1:30101"
    asia-south-worker-1 = "127.0.0.1:30201"

    [Storage.SyncAddrs.subnet-2]
    Public = "127.0.0.1:32000"
    Listen = "127.0.0.1:32000"

    [Storage.Peers.subnet-2]
    eu-west-worker-2 = "127.0.0.1:30002"
    us-west-worker-2 = "127.0.0.1:30102"
    asia-south-worker-2 = "127.0.0.1:30202"

    [Storage.SyncAddrs.subnet-3]
    Public = "127.0.0.1:33000"
    Listen = "127.0.0.1:33000"

    [Storage.Peers.subnet-3]
    eu-west-worker-3 = "127.0.0.1:30003"
    us-west-worker-3 = "127.0.0.1:30103"
    asia-south-worker-3 = "127.0.0.1:30203"
